// stores/products.ts
import { defineStore } from "pinia"

const placeholderImg = "/images/shopping.webp"

export const useProductsStore = defineStore("products", {
  state: () => ({
    newArrivals: [
      {
        id: 1,
        title: {
          uk: "Зволожувальний крем для обличчя",
          en: "Moisturizing Face Cream",
        },
        description: {
          uk: "Найкращий зволожувальний крем для обличчя з природними компонентами.",
          en: "The best moisturizing face cream with natural ingredients.",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 299,
        discount: { amount: 30, percentage: 0 },
        rating: 4.8,
      },
      {
        id: 2,
        title: {
          uk: "Гіалуронова сироватка",
          en: "Hyaluronic Serum",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 350,
        discount: { amount: 0, percentage: 10 },
        rating: 4.7,
      },
      {
        id: 3,
        title: {
          uk: "Очищувальна пінка для вмивання",
          en: "Cleansing Facial Foam",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 220,
        discount: { amount: 0, percentage: 0 },
        rating: 4.5,
      },
      {
        id: 4,
        title: {
          uk: "Патчі під очі з золотом",
          en: "Gold Under-Eye Patches",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 180,
        discount: { amount: 0, percentage: 15 },
        rating: 4.6,
      },
      {
        id: 5,
        title: {
          uk: "Тональний крем з SPF 30",
          en: "Foundation with SPF 30",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 430,
        discount: { amount: 0, percentage: 0 },
        rating: 4.9,
      },
      {
        id: 6,
        title: {
          uk: "Матова губна помада",
          en: "Matte Lipstick",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 199,
        discount: { amount: 0, percentage: 0 },
        rating: 4.4,
      },
      {
        id: 7,
        title: {
          uk: "Лак для нігтів нюдовий",
          en: "Nude Nail Polish",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 150,
        discount: { amount: 0, percentage: 0 },
        rating: 4.1,
      },
      {
        id: 8,
        title: {
          uk: "Антивікова сироватка",
          en: "Anti-Aging Serum",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 520,
        discount: { amount: 0, percentage: 20 },
        rating: 4.9,
      },
      {
        id: 9,
        title: {
          uk: "Скраб для тіла кавовий",
          en: "Coffee Body Scrub",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 160,
        discount: { amount: 0, percentage: 5 },
        rating: 4.3,
      },
      {
        id: 10,
        title: {
          uk: "Міцелярна вода",
          en: "Micellar Water",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 190,
        discount: { amount: 0, percentage: 0 },
        rating: 4.5,
      },
    ],

    topSelling: [
      {
        id: 11,
        title: {
          uk: "Крем для рук живильний",
          en: "Nourishing Hand Cream",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 120,
        discount: { amount: 0, percentage: 10 },
        rating: 4.8,
      },
      {
        id: 12,
        title: {
          uk: "Шампунь проти випадіння волосся",
          en: "Anti Hair Loss Shampoo",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 260,
        discount: { amount: 0, percentage: 0 },
        rating: 4.7,
      },
      {
        id: 13,
        title: {
          uk: "Бальзам для губ",
          en: "Lip Balm",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 99,
        discount: { amount: 0, percentage: 0 },
        rating: 4.3,
      },
      {
        id: 14,
        title: {
          uk: "Кондиціонер для волосся",
          en: "Hair Conditioner",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 230,
        discount: { amount: 0, percentage: 5 },
        rating: 4.6,
      },
      {
        id: 15,
        title: {
          uk: "Сироватка проти акне",
          en: "Acne Treatment Serum",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 310,
        discount: { amount: 0, percentage: 0 },
        rating: 4.8,
      },
      {
        id: 16,
        title: {
          uk: "Маска для обличчя з вугіллям",
          en: "Charcoal Face Mask",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 140,
        discount: { amount: 0, percentage: 0 },
        rating: 4.2,
      },
      {
        id: 17,
        title: {
          uk: "Парфумована вода жіноча",
          en: "Women’s Perfume",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 680,
        discount: { amount: 0, percentage: 20 },
        rating: 4.9,
      },
      {
        id: 18,
        title: {
          uk: "Маска для волосся кератинова",
          en: "Keratin Hair Mask",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 250,
        discount: { amount: 0, percentage: 0 },
        rating: 4.7,
      },
      {
        id: 19,
        title: {
          uk: "Туш для вій об'ємна",
          en: "Volumizing Mascara",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 220,
        discount: { amount: 0, percentage: 0 },
        rating: 4.5,
      },
      {
        id: 20,
        title: {
          uk: "Олія для кутикули",
          en: "Cuticle Oil",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 130,
        discount: { amount: 0, percentage: 10 },
        rating: 4.4,
      },
    ],

    relatedProducts: [
      {
        id: 21,
        title: {
          uk: "Гель для брів фіксуючий",
          en: "Brow Fixing Gel",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 160,
        discount: { amount: 0, percentage: 0 },
        rating: 4.6,
      },
      {
        id: 22,
        title: {
          uk: "Палетка тіней нейтральних",
          en: "Neutral Eyeshadow Palette",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 480,
        discount: { amount: 0, percentage: 10 },
        rating: 4.9,
      },
      {
        id: 23,
        title: {
          uk: "Праймер під макіяж",
          en: "Makeup Primer",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 210,
        discount: { amount: 0, percentage: 0 },
        rating: 4.4,
      },
      {
        id: 24,
        title: {
          uk: "Рум'яна кремові",
          en: "Cream Blush",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 170,
        discount: { amount: 0, percentage: 0 },
        rating: 4.3,
      },
      {
        id: 25,
        title: {
          uk: "База під тіні",
          en: "Eyeshadow Base",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 190,
        discount: { amount: 0, percentage: 15 },
        rating: 4.7,
      },
      {
        id: 26,
        title: {
          uk: "Матуючий тональний крем",
          en: "Matte Foundation",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 410,
        discount: { amount: 0, percentage: 0 },
        rating: 4.8,
      },
      {
        id: 27,
        title: {
          uk: "Олія для тіла ароматизована",
          en: "Scented Body Oil",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 250,
        discount: { amount: 0, percentage: 5 },
        rating: 4.5,
      },
      {
        id: 28,
        title: {
          uk: "Крем навколо очей",
          en: "Eye Cream",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 300,
        discount: { amount: 0, percentage: 0 },
        rating: 4.6,
      },
      {
        id: 29,
        title: {
          uk: "Гель для вмивання з алое",
          en: "Aloe Facial Cleanser",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 170,
        discount: { amount: 0, percentage: 0 },
        rating: 4.4,
      },
      {
        id: 30,
        title: {
          uk: "Спрей для волосся термозахисний",
          en: "Heat Protection Hair Spray",
        },
        srcUrl: placeholderImg,
        gallery: [placeholderImg],
        price: 260,
        discount: { amount: 0, percentage: 10 },
        rating: 4.7,
      },
    ],
  }),
})
